-- SCRIPT PARA CREAR TABLAS DE BIBLIOTECA VIRTUAL
-- Ejecutar en Oracle Database
-- sqlplus usuario/password@database @crear_tablas_biblioteca.sql


-- TABLA: USUARIOS
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    contraseña VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('USUARIO', 'BIBLIOTECARIO')) NOT NULL
);


-- TABLA: LIBROS
CREATE TABLE libros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    autor VARCHAR2(100),
    categoria VARCHAR2(100),
    stock NUMBER DEFAULT 1 CHECK (stock >= 0)
);


-- TABLA: PRÉSTAMOS
CREATE TABLE prestamos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_libro NUMBER NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE,
    fecha_devolucion DATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'DEVUELTO', 'VENCIDO')),
    
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id),
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES libros(id)
);


-- Índices para la tabla usuarios
CREATE INDEX idx_usuarios_correo ON usuarios(correo);
CREATE INDEX idx_usuarios_rol ON usuarios(rol);

-- Índices para la tabla libros
CREATE INDEX idx_libros_titulo ON libros(titulo);
CREATE INDEX idx_libros_autor ON libros(autor);
CREATE INDEX idx_libros_categoria ON libros(categoria);
CREATE INDEX idx_libros_stock ON libros(stock);

-- Índices para la tabla prestamos
CREATE INDEX idx_prestamos_usuario ON prestamos(id_usuario);
CREATE INDEX idx_prestamos_libro ON prestamos(id_libro);
CREATE INDEX idx_prestamos_estado ON prestamos(estado);
CREATE INDEX idx_prestamos_fecha_prestamo ON prestamos(fecha_prestamo);
CREATE INDEX idx_prestamos_fecha_devolucion ON prestamos(fecha_devolucion);



-- DATOS DE PRUEBA
-- Insertar usuario de prueba
INSERT INTO usuarios (nombre, correo, contraseña, rol) VALUES
('Carlos López', 'carlos.lopez@biblioteca.com', 'admin123', 'BIBLIOTECARIO');

-- Insertar libros de prueba
INSERT INTO libros (titulo, autor, categoria, stock) VALUES
('El Señor de los Anillos', 'J.R.R. Tolkien', 'Fantasía', 5);

INSERT INTO libros (titulo, autor, categoria, stock) VALUES
('Cien años de soledad', 'Gabriel García Márquez', 'Realismo Mágico', 3);

INSERT INTO libros (titulo, autor, categoria, stock) VALUES
('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela', 4);

INSERT INTO libros (titulo, autor, categoria, stock) VALUES
('1984', 'George Orwell', 'Ciencia Ficción', 2);

INSERT INTO libros (titulo, autor, categoria, stock) VALUES
('El Principito', 'Antoine de Saint-Exupéry', 'Literatura Infantil', 6);




-- INSTRUCCIONES DE EJECUCIÓN
/*
Para ejecutar este script:

1. Conectar a Oracle:
   sqlplus usuario/password@database

2. Ejecutar el script:
   @crear_tablas_biblioteca.sql

3. Verificar la creación:
   SELECT table_name FROM user_tables WHERE table_name IN ('USUARIOS', 'LIBROS', 'PRESTAMOS');

4. Después de crear las tablas, ejecutar el script de procedimientos:
   @biblioteca_procedures.sql
*/ 